#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Nitinyourdad_REPO == "hulk" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL05pdGlueW91cmRhZC9odWxrdXNlcmJvdC9hcmNoaXZlL2h1bGsuemlw" | base64 -d
    elif [[ $Nitinyourdad_REPO == "hulk" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL05pdGlueW91cmRhZC9odWxrdXNlcmJvdC9hcmNoaXZlL2h1bGsuemlw" | base64 -d
    elif [[ $Nitinyourdad_REPO =~ $regex ]]
    then
        if [[ $Nitinyourdad_REPO_BRANCH ]]
        then
            echo "${Nitinyourdad_REPO}/archive/${Nitinyourdad_REPO_BRANCH}.zip"
        else
            echo "${Nitinyourdad_REPO}/archive/Hulk.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL05pdGlueW91cmRhZC9odWxrdXNlcmJvdC9hcmNoaXZlL2h1bGsuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Hulkbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HulkPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HulkPATH
    echo "    Starting Hulk    "
    echo "
                          Hulk
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
