#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SURTUR_REPO == "surturbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL21hZmlhcmlzaGFiaC9zdXJ0dXJ1c2VyLWJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $SURTUR_REPO == "SURTURBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL21hZmlhcmlzaGFiaC9zdXJ0dXJ1c2VyLWJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $SURTUR_REPO =~ $regex ]]
    then
        if [[ $SURTUR_REPO_BRANCH ]]
        then
            echo "${SURTUR_REPO}/archive/${SURTUR_REPO_BRANCH}.zip"
        else
            echo "${SURTUR_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL21hZmlhcmlzaGFiaC9zdXJ0dXJ1c2VyLWJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="surturbot.zip"
    echo "  Downloading SurturBot source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $SURTURPATH
    echo "    Starting SurturBot    "
    echo "SURTURBOT
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m surturbot
}

_set_bot
